### ISSUE TITLE
compose error

### ISSUE THREAD

**Issue by johannes-riesterer** [ScaleIT-Org/nodejs-app-skeleton#1]
Error: Failed to transpile program
    at BuildError.Error (native)
    at new BuildError (/opt/app/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /opt/app/node_modules/@ionic/app-scripts/dist/transpile.js:137:20
    at transpileWorker (/opt/app/node_modules/@ionic/app-scripts/dist/transpile.js:103:12)
    at Object.transpile (/opt/app/node_modules/@ionic/app-scripts/dist/transpile.js:61:12)
    at buildProject (/opt/app/node_modules/@ionic/app-scripts/dist/build.js:97:78)
    at /opt/app/node_modules/@ionic/app-scripts/dist/build.js:47:16

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! nodejs-app-skeleton@0.0.1 build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodejs-app-skeleton@0.0.1 build script 'ionic-app-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodejs-app-skeleton package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodejs-app-skeleton
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodejs-app-skeleton
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/app/npm-debug.log
ERROR: Service 'nodejs-app-skeleton' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 1

**Comment by Kuhno92** [comment]
fixed some issues with commit 1fe6dde4fcda0d68d2819e9d56c900c6e901df76 and 9f5dfc740f6bf00adb717872a9b17b0e9a73990e 
please give it another try.
Your issue should hopefully be fixed now

**Comment by frostyandy2k** [comment]
Issue is fixed, thanks for reporting and thanks for fixing.
