### ISSUE TITLE
Can we compile this for ARM ?

### ISSUE THREAD

**Issue by frostyandy2k** [ScaleIT-Org/nodejs-app-skeleton#10]

**Comment by Kuhno92** [comment]
Which part of the application do you want to compile for ARM?
There are nodejs binaries for ARM available and the frontend are just static files? or do you want to execute the frontend build process on arm machines?

**Comment by frostyandy2k** [comment]
We just need a container that can run on an ARM (like for the Raspberry Pi).

So just the image needs to be runnable on ARM, but I do not know the details on how to manage that.

* Need to figure out if the base docker image we are using has an ARM version
* We may need a special branch for the ARM build
* Create a test image to demonstrate that it works and upload it to dockerhub

**Comment by frostyandy2k** [comment]
Moved to https://github.com/ScaleIT-Org/ionic-app-skeleton/issues/4
