### ISSUE TITLE
Double assets directories?

### ISSUE THREAD

**Issue by frostyandy2k** [ScaleIT-Org/nodejs-app-skeleton#15]
Why are there double diretories?

* nodejs-app-skeleton/src/assets
* nodejs-app-skeleton/src/pages/assets

**Comment by Kuhno92** [comment]
Was used by the initial ionic app template to group page dependent assets and global assets.
Can be merged together if not needed.

**Comment by frostyandy2k** [comment]
Yes we should merge them otherwise it's confusing. Does the second assets directory work (is it hosted by the node.js server)?

**Comment by Kuhno92** [comment]
idk but it is now removed with 049a41400f4f426567ddfe751a10a87ca946a5b5.
So isseu closed!
