### ISSUE TITLE
Update Deprecated Libraries

### ISSUE THREAD

**Issue by frostyandy2k** [ScaleIT-Org/nodejs-app-skeleton#2]
npm WARN deprecated babili@0.1.2: babili has been renamed to babel-minify. Please update to babel-minify
npm WARN deprecated babel-preset-babili@0.1.4: babili has been renamed to babel-minify. Please update to babel-preset-minify
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys

**Comment by Kuhno92** [comment]
Fixed with b2a490cf5d19b71e595fcf0061281192ccc16ced
