### ISSUE TITLE
Fix exit code 137 Docker PID Zombie

### ISSUE THREAD

**Issue by frostyandy2k** [ScaleIT-Org/nodejs-app-skeleton#3]

**Comment by frostyandy2k** [comment]
Maybe use sysvinit? Check for alpine compatibility
 https://news.ycombinator.com/item?id=14581820

**Comment by Kuhno92** [comment]
Fixed with 703356665b6602d717ea48c2df2526da1065efe7

**Comment by Kuhno92** [comment]
Bitte Testen ob das Funktioniert @liskior oder @frostyandy2k. Falls Ja issue bitte schließen!

**Comment by frostyandy2k** [comment]
Tested, works, good job
