### ISSUE TITLE
Adapt folder structure to the ScaleIT template

### ISSUE THREAD

**Issue by RobinFischer** [ScaleIT-Org/nodejs-app-skeleton#8]
According to the ScaleIT documentation each app should be build using the following folder structure template:

![grafik](https://user-images.githubusercontent.com/29731529/36259192-b26193f4-125d-11e8-9991-f427f8e5588a.png)

Only apps that follow this folder template are considered "Industrie 4.0 Ready".
More information on app readiness can be found here:
http://scaleit-platform-documentation.readthedocs.io/en/latest/app_readiness.html#app-containers-docker-subsystem

I would consider moving or renaming the file structure, so it fits to the template.

**Comment by frostyandy2k** [comment]
Will create a Meta-Project repository for this and add guidelines on how to add it as git submodule.

**Comment by frostyandy2k** [comment]
https://github.com/ScaleIT-Org/sapp-i40-app-skeleton
